### ISSUE TITLE
UI: put sorting indicators closer to associated column header

### ISSUE THREAD

**Issue by swilde** [Intevation/intelmq-fody#11]
I like the little Icons indicating the current sorting of the (events) table.

But I'm confused by the placement, the indicators are aligned on the right end of the columns so they are quite far from the associated column header and very close to the column header of the next column.  Thereby it looks like they are belonging to another column:

![fody-report](https://cloud.githubusercontent.com/assets/1741483/21006826/e9d29244-bd3a-11e6-9abc-6466ebbeedee.png)

**Comment by bernhardreiter** [comment]
Thanks for the report, I've seen this problem happening when the browser window gets quite large.
