### ISSUE TITLE
elevate url length limits when asking for more events

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#12]
@swilde assumes that Browsers have a practical URL request limit of ~2000 Bytes.

This would only allow to ask for about ~160 events ids via the current /getEvents? ids=
interface.

Ideas to change this:
 * Directly ask for all events for one ticket.
 * Use a post method to ask for the ids

**Comment by swilde** [comment]
A good summary on the problem can be found here: 
http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

When we define a small(er) set of supported browsers we could get a higher boundary for the maximal URI length, but as I would prefer a more intelligent solution like the proposed ones anyway.

FWIW I like "Directly ask for all events for one ticket." which loads of the logic/work to the database best.

**Comment by bernhardreiter** [comment]
Once we want to load many events, we want to load in chunks, so a simple method that get us everything for one ticket is not enough.

**Comment by bernhardreiter** [comment]
0b46fc3f7c039120445c54cd2c9d1e883afca87d uses a directly load events. 
Tries loading up to 10,000 events (tested with 5,000 events), which seems to be in the 10 seconds
range. The loading animation makes this bearable.
