### ISSUE TITLE
Allow editing/writing of contactdb entries

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#17]
fody-0.2.0-dev can display contactdb entries in the "auto" and "manual" tables with ASNs and email addresses.

The next step is to make them writeable/editable.

27a27a9ed70cb44b35fe5b99e242360af1ab2600 already prepares a few buttons and an extra orgcard display for org to be edited.

**Comment by bernhardreiter** [comment]
3afab4547884ed7569732eb48f14d81cdbdf3b26 accepts changes to some orgcard attributes in the editable view and sends a whole package towards the server. (Can be tested with the latest contactdb_api from the mailgen repo.)

**Comment by bernhardreiter** [comment]
62b87aaecddf1fdbfba4329e3d3220421bb17734 allows editing of all (relevant) attributes.

**Comment by bernhardreiter** [comment]
The server side and fody haven been improved to allow creation of new contactdb entries.

**Comment by bernhardreiter** [comment]
5e3f783025dc585b8c78f0048f5470e7ed214ab1 and mailgen:2f66fd8fc17e57ea32024d8f4ed1010c4cfff456 allow first "create" and "delete" roundtrips on the manual contacts

**Comment by bernhardreiter** [comment]
with e4f203fb5a01bcf05f8c01bec53abc3ee31de1e6 the basic functionality of creating, deleting and updating entrie is there. (Needs testing now.)

**Comment by dmth** [comment]
Why did you assign me to this issue?

**Comment by bernhardreiter** [comment]
@dmth Please confirm, that the basic functionality is there. Without defects.

**Comment by bernhardreiter** [comment]
With inhibitions and substrings search added, this should work now sufficiently good.
