### ISSUE TITLE
Dashboard: wiggles

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#28]
With e4f203fb5a01bcf05f8c01bec53abc3ee31de1e6 if you resize the browser windows
to the point where the vertical scrollbar is going to appear or vanish, the browser enters s resizing loop.
Reported by @dmth 

(tested on a desktop with Chromium	56.0.2924.76 and  firefox 45.7.0)

**Comment by bernhardreiter** [comment]
Also reproduced and reported upstream https://github.com/misterGF/CoPilot/issues/18

**Comment by rrenkert** [comment]
https://github.com/Intevation/intelmq-fody/commit/a052cd19b11fa202472f9985dbf0ec89984f36af fixes this problem by always showing the vertical scrollbar for the page body.

**Comment by bernhardreiter** [comment]
Testing with Chromium	57.0.2987.98 and Firefox  52.0.1:
 * Problem is gone! Thanks @rrenkert 
 * The scrollbar is only shown if the page contents overflows, which is good. (From the comment above I had assumed that it would be also shown if the page contents is not overflowing.)
