### ISSUE TITLE
Update dependencies for build tests (20161116)

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#3]
The installation step will lead to a number of dependency warnings:
```
yarn
yarn install v0.17.0

warning nightwatch > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning chromedriver > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning nightwatch > mocha-nightwatch > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning nightwatch > mocha-nightwatch > glob > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning nightwatch > mocha-nightwatch > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
warning Incorrect peer dependency "eslint-plugin-promise@>=3.3.0"
```

```
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but none was installed.
```

They seem to be  for the build test framework, which is not used currently and thus it is of minor importance to fix it.  Missing fsevents is fine.

- [ ] Incorrect peer dependency "eslint-plugin-promise@>=3.3.0
- [ ] nightwatch dependencies
- [ ] chromedriver

**Comment by bernhardreiter** [comment]
@MaximilianKrambach as you took a look lately, is this report still valid?

**Comment by MaximilianKrambach** [comment]
After a look at the current  yarn.lock, I can confirm that these issues are resolved in my last cleanup/update:

- minimatch has version 3.0.4
- graceful-fs has version 4.2.3
- eslint-plugin-promise is present in version 4.2.1
- nightwatch and npmconf are not present anymore


The only of these warnings likely to be still present is the fsevent (which is expected)
