### ISSUE TITLE
Enable backend to serve multiple connections faster using python threads

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#30]
Right now contactdb_api and checkticket.py use a global variable for the psycopg2 database connection. This will allow several threads to interfere with each other within one transaction.

With checkticket.py this did not matter much as it is read only.
With contactdb_api commit now implemented it can be more of a problem, but load can be handled by one process.
We will certainly need more requests once we go into serving queries that take longer, e.g. for statistics.

Technical idea: Use the [psycopg2.pool.ThreadedConnectionPool()](http://initd.org/psycopg/docs/pool.html) class.

**Comment by bernhardreiter** [comment]
On of my test was conducted with
```python
@hug.get()
def sleep(secs:float, request):
    import time
    if secs < 300:
       time.sleep(secs)
    return {"wsgi.multithread": request.env["wsgi.multithread"],
            "wsgi.multiprocess": request.env["wsgi.multiprocess"]}
```

(as now documented in
https://github.com/Intevation/intelmq-mailgen/blob/8f605fdda524a98e4a5f5ca6a7eca0ea812683f8/extras/checkticket-spa/checkticket.py )

showed that apache was using multiprocess anyway on Ubuntu and setting of threads=15 did not show wsgi.multithread as true.

**Comment by bernhardreiter** [comment]
Tagging minor value, because Fody will mostly run in an environment where there are not many concurrent clients and a single process setup with apache (which means that apache spawns one process per httpd) is enough to handle a small to medium load.

**Comment by dmth** [comment]
> Tagging minor value, because Fody will mostly run in an environment where there are not many concurrent clients and a single process setup with apache (which means that apache spawns one process per httpd) is enough to handle a small to medium load.

We may need to revise this. Can we define the amount of "concurrent clients"?

**Comment by bernhardreiter** [comment]
> Can we define the amount of "concurrent clients"?

Rough guess: We are good for at least 100 working places (because they won't do more than a few concurrent requests per second).

**Comment by dmth** [comment]
> Rough guess: We are good for at least 100 working places (because they won't do more than a few concurrent requests per second).

That is sufficient for our case.

**Comment by bernhardreiter** [comment]
Closing this issue, because it is more a backend capability, see https://github.com/Intevation/intelmq-fody-backend/issues/12 .
