### ISSUE TITLE
Disable the possibility to create empty Org-Cards

### ISSUE THREAD

**Issue by dmth** [Intevation/intelmq-fody#34]
In Version: 0.2.1-dev it is possible to store empty Org-Cards (Orgs without names or other attributes). Nevertheless it is not possible to search for these Orgs or to delete these Orgs.

**Comment by bernhardreiter** [comment]
Fixed when using contactdb_api with https://github.com/Intevation/intelmq-mailgen/commit/9628deccf8040632fc840bb4e38872a5958fe87f
