### ISSUE TITLE
Find out how to use url values from a directly used subpage

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#36]
This is split out from #2:

How could be use a parameter to a subpage in the corresponding vue file.
For example when calling directly in the webbrowser

`/tickets?ticket=14`

How does this end up in Tickets.vue to show ticket number '14'?
Actually this should also work, when using a sublink from a different page.
Like on tickets, you would want to jump to `/contacts?searchasn=49234` or so.

**Comment by bernhardreiter** [comment]
To clarify: this is about the **external and internal** use case.

**Comment by rrenkert** [comment]
Corresponds with #27.
In the router (https://router.vuejs.org/en/api/route-object.html) all URL parameters are available and can be used to set the state of a component. Reactivity of the application should do the rest.

**Comment by dmth** [comment]
See https://github.com/Intevation/intelmq-fody/commit/8ef327c00487c403b5c480280c105cace789ecff

With https://github.com/Intevation/intelmq-fody-api/commit/4ea257d82e126d33d5230d17e04b7058367c57ff in fody-api Linking / bookmarking does also work.
