### ISSUE TITLE
Export charts for printing

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#37]
When displaying charts, they should be exportable for printing.

Possible formats: PDF, SVG.

SVG may have advantages if your office suit can do it. Libreoffice has SVG import.
Microsoft Office seems to have one since version 2016. 

For the web using an HTML5 canvas with SVG seems to be the best technical way and should be done first.  A possible extension is to transform this svg into pdf. Maybe with something like https://github.com/ahwolf/jsPDF/blob/master/jspdf.plugin.svgToPdf.js (also see server side solutions like https://d3export.housegordon.org/).

**Comment by bernhardreiter** [comment]
Export of client side generated files can happen via data URIs, see Resources tab on http://caniuse.com/#feat=datauri

**Comment by bernhardreiter** [comment]
The http://www.chartjs.org/docs/#notes-charting-library-comparison show that chart.js uses canvas, so with planned export we are probably better off with SVG generation, found an example for vue integration of d3: 
https://github.com/johnnynotsolucky/samples/tree/master/vuejs-d3

**Comment by dmth** [comment]
Integration of SVG in Microsoft Word 2016 seems to be available.

https://support.office.com/en-us/article/Insert-SVG-images-in-Microsoft-Office-69f29d39-194a-4072-8c35-dbe5e7ea528c

**Comment by bernhardreiter** [comment]
Clarifications within our project shows: SVG is good enough, if it can be used in libreoffice. Which means we need to have the style within the attributes of the SVG tags (see #38)

**Comment by bernhardreiter** [comment]
8a31f0c5a88d1f8ca8e5108cd9cffcadfa01e021 can export an SVG that opens in libreoffice.

**Comment by bernhardreiter** [comment]
Except for the translation to the right, the implemented export works for libreoffice  (tested with  5.2.5.1)
and inkscape (tested with 0.48.5)

**Comment by bernhardreiter** [comment]
Done except #41
