### ISSUE TITLE
Logo for Fody

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#47]
It would be nice to have a logo for fody.
(Right now it still uses the logo inherited from Copilot see files `logo*.png` in [the sources](https://github.com/Intevation/intelmq-fody/tree/da94e9050213337c8073fd5cb988e8fe13420fa1/static/img) and the left upper corner of the following [screenshot of fody v0.2.0-dev](https://cloud.githubusercontent.com/assets/8190008/22743973/271a7d76-ee1c-11e6-882e-bbc629e97ace.png).)

The name of fody is derived from the [weaver birds](https://en.wikipedia.org/wiki/Rodrigues_fody). As they build nice looking nests.

I am envisioning a logo that uses the intelmq logo graphics formed a bit like a weavers nest in a circle.

Technical requirements:
 * Needs to be able to replace the four `logo*.png` files as linked above.
 * If a vector source is used to produce the four files, it shall be SVG and included in addition to 
   some instructions how to get the four files out of the SVG.
 * The SVG file must work in inkscape.
 * the first requirement basically comes down to: "flat" design, one color, high contrast
 * a plus is, if it can also be used in smaller setting like a favicon
 * it shall graphically let people make a connection to the  graphical part of the [IntelMQ logo](https://github.com/certtools/intelmq/blob/master/docs/images/Logo_Intel_MQ.svg)

**Comment by bernhardreiter** [comment]
Technical idea, take the graphical upper part of ` Logo_Intel_MQ.svg`, re-group parts and bend it
to look like a complete round coarse weavers nest.  (possible inspiration: https://commons.wikimedia.org/wiki/Category:Ploceus_nests but without entry hole and without holding bag handle)

**Comment by bernhardreiter** [comment]
This will be worked on from my side (I possibly subcontract someone).

**Comment by bernhardreiter** [comment]
Here aredrafts by Marcel 'Howly' Newman (whom I've contracted) in context. 
Which one do you like best? (It then would need to be worked out.)

![fody-20170508-logo1](https://cloud.githubusercontent.com/assets/8190008/25806065/55bcaaec-3402-11e7-9597-61adf190777a.png)
![fody-20170508-logo2](https://cloud.githubusercontent.com/assets/8190008/25806069/59ee8c84-3402-11e7-8b5f-ada091879fde.png)

An alternative with only three 'connections':
![a1](https://cloud.githubusercontent.com/assets/8190008/25806300/03d59c24-3403-11e7-8a1c-c4c153da7d32.png)

**Comment by dmth** [comment]
As already discussed with @bernhardreiter the logo reminds me of chrome/chromium and also https://syncthing.net/

In our discussion I preferred the variant with four connections (white on blue), nevertheless, the white on black three-connected logo has also a nice touch, today.

**Comment by bernhardreiter** [comment]
Another variant:
![fody-20170509-logo4](https://cloud.githubusercontent.com/assets/8190008/25840152/f0d93a84-349a-11e7-8e90-4dfa47fb5d31.png)

**Comment by bernhardreiter** [comment]
Here is an overview of all variants so far:
![logo-overview-1](https://cloud.githubusercontent.com/assets/8190008/25841260/b8437b44-349f-11e7-8526-5def1552bac0.png)

**Comment by dmth** [comment]
The outline in No. 4 is to large. Can you provide an inverted variant of No. 1?

**Comment by bernhardreiter** [comment]
> The outline in No. 4 is to large. 

Do you refer to the thickness of the surrounding circle stroke? Or do you mean the complete size?

> Can you provide an inverted variant of No. 1?

Like No. 4? Potentially could, would it really help much?

**Comment by dmth** [comment]
> Do you refer to the thickness of the surrounding circle stroke? Or do you mean the complete size?

I refer to the thickness of the surrounding circle stroke

**Comment by bernhard-herzog** [comment]
No. 4 is probably best, but as Dustin said, the outer circle should have the same thickness as the other edges. Or is that circle not supposed to be part of graph suggested by the interior of the circle?

**Comment by swilde** [comment]
I think that one and two best reassemble the original idea of an stylized weavers nest, but from the over all optics I'd support the vote for number four, which reminds me a little bit of an steering wheel, which isn't the worst association in the context of the actual web application.

My 2¢, but overall I don't have any strong preferences regarding the logo...

**Comment by bernhardreiter** [comment]
With Howly liking 3 and 4 and me prefering 2, we have a winner:

**Most people like "No 4, with a slightly improved outline stroke"**

Distribution:
 1. ` `
 2. `*`
 3. `*`
 4. `****`

**Comment by bernhardreiter** [comment]
The new logo is in with 320a54326d406137bd904dc25cabed7b8aeb1fe9
![fody-20170517-logo1](https://cloud.githubusercontent.com/assets/8190008/26149825/11ac05b8-3afc-11e7-8a5c-ca983e930b75.png)
