### ISSUE TITLE
On searches leading and trailing whitespace should be stripped

### ISSUE THREAD

**Issue by swilde** [Intevation/intelmq-fody#48]
When searching e.g. for a CIDR the search for "203.0.113.0/24 " will currently not find the organization responsible for 203.0.113.0/24, due to the trailing white space.  As such additionally whit space is easily introduced by sloppy c&p and hard to detect for the human user it should be ignored by the search.

**Comment by dmth** [comment]
Working on It right now. It's a Backend Problem.

**Comment by bernhardreiter** [comment]
> Working on It right now. It's a Backend Problem.

I'd fix it in the frontend, just strip the spaces.

**Comment by dmth** [comment]
arg! I commented on the wrong problem. I meant to work on the search of specific IPs

**Comment by dmth** [comment]
> I'd fix it in the frontend, just strip the spaces.

Shouldn't the backend also make sure of this?

**Comment by bernhardreiter** [comment]
Searching for a name with leading or trailing spaces could be on purpose,
this is why I believe it is a frontend thing.

**Comment by dmth** [comment]
> Searching for a name with leading or trailing spaces could be on purpose, this is why I believe it is a frontend thing.

If you do this on purpose, the Frontend should also not strip those characters.

**Comment by bernhardreiter** [comment]
The frontend can decide.

**Comment by bernhardreiter** [comment]
@dmth  after considering it, I agree that you are right: for this kind of search leading and trailing whitespace does not make sense, so making the backend robust is better.

**Comment by dmth** [comment]
@bernhardreiter This issue is closed, did you also enhance the backend?

**Comment by bernhardreiter** [comment]
@dmth Yes I've fixed the backend, as can be seen in the closing note above where the commit with the fix in the backend is given.

**Comment by dmth** [comment]
Thanks
