### ISSUE TITLE
Too many contacts will slow down/halt browser.

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#51]
When trying to display too many Contact entries (technically called OrgCard) the browser is getting slow or halting completely.

@dmth gave 6000 orgcards as a limit where the system got unusable, es an example you can easily get as many results if you search for an /0 network.

## Technical ideas
A quick way to prevent this would be to give an upper limit for displaying the orgs. However it shall be displayed to the user somehow and it may need a way for the user to override the option and just wait.

As subpoints that have a general value: 
 * We'd need a way to display messages regarding the the state of search results or other conditions.
 * If we had a "desk-concept" of found org-object, we could offer to just add the first 100 to the displayed list or so.

**Comment by dmth** [comment]
> @dmth gave 6000 orgcards as a limit where the system got unusable, es an example you can easily get as many results if you search for an /0 network.

This does not represent the lower boundary. The system might get unusable earlier.
