### ISSUE TITLE
broken links in readme

### ISSUE THREAD

**Issue by wagner-certat** [Intevation/intelmq-fody#58]
> For data to be retrieved, you need to serve the [checkticket](https://github.com/Intevation/intelmq-mailgen/tree/master/extras/checkticket-spa) and [contactdb](https://github.com/Intevation/intelmq-mailgen/tree/master/extras/contactdb_api) apis via http for your Intelmq setup.

Both links are broken

**Comment by bernhardreiter** [comment]
@wagner-certat thanks for the hint!
