### ISSUE TITLE
On tool switch: TypeError: event.toElement is undefined

### ISSUE THREAD

**Issue by wagner-certat** [Intevation/intelmq-fody#78]
Running current master (v0.5.2-76-g254a162) with `yarn run dev` I see this error in the console every time I click one of the tools on the left window border:

> TypeError: event.toElement is undefined

Everything works expected although, I don't see negative impact.

Most probably coming from this code:
https://github.com/Intevation/intelmq-fody/blob/254a16270a481887720e55acb073000643efb7eb/src/components/Dash.vue#L132-L133

The `event` object here looks like this here:
```
click
altKey: false
bubbles: true
button: 0
buttons: 0
cancelBubble: false
cancelable: true
clientX: 122
clientY: 248
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 1
eventPhase: 0
explicitOriginalTarget: <a class="router-link-exact-active router-link-active" href="/stats">
isTrusted: true
layerX: 122
layerY: 29
metaKey: false
movementX: 0
movementY: 0
mozInputSource: 1
mozPressure: 0
offsetX: 0
offsetY: 0
originalTarget: <a class="router-link-exact-active router-link-active" href="/stats">
pageX: 122
pageY: 248
rangeOffset: 0
rangeParent: null
region: ""
relatedTarget: null
returnValue: false
screenX: 159
screenY: 422
shiftKey: false
srcElement: <a class="router-link-exact-active router-link-active" href="/stats">
target: <a class="router-link-exact-active router-link-active" href="/stats">
timeStamp: 5539
type: "click"
view: Window http://localhost:8080/stats
which: 1
x: 122
y: 248
<get isTrusted()>: function isTrusted()
<prototype>: MouseEventPrototype { initMouseEvent: initMouseEvent(), getModifierState: getModifierState(), initNSMouseEvent: initNSMouseEvent(), … }
```

**Comment by MaximilianKrambach** [comment]
> Most probably coming from this code:
> https://github.com/Intevation/intelmq-fody/blob/254a16270a481887720e55acb073000643efb7eb/src/components/Dash.vue#L132-L133
> 
> The `event` object here looks like this here:

A quick look shows that this is an issue with the (non-standard) "toElement" not being recognized by some browsers. It can safely be switched with "event.target" (which will move this problem to ancient Internet Explorer versions < 9).

I successfully tested this change in chromium (78.0) and firefox (70.0.1).

**Comment by bernhardreiter** [comment]
@MaximilianKrambach feel free to commit. :)
