### ISSUE TITLE
Statistics: No feedback shown if search result is empty

### ISSUE THREAD

**Issue by wagner-certat** [Intevation/intelmq-fody#79]
If the search returns no results, no feedback at all is shown in the UI. I found this line in the source most probably responsible:

https://github.com/Intevation/intelmq-fody/blob/254a16270a481887720e55acb073000643efb7eb/src/components/dash/Stats.vue#L102

Removing this restriction gives the expected result "Events Total for this Query 0". Is there a specific reason that no feedback is shown or could this be changed?

**Comment by bernhardreiter** [comment]
This has been fixed with https://github.com/Intevation/intelmq-fody/releases/tag/v0.9.1 last September. (Sorry for closing this so late here.)
