### ISSUE TITLE
Event detail entries do not open sometimes

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody#82]
Some times the event details for an entry do not open.

How to reproduce:
 * Select the Stats page
 * Search for some events for a time frame (that are below 20k events)
 * click on "details"
 * open an entry, e.g. by clicking on the plus
 * change the search query, e.g. by adding a rule for a "destination ASN", load the data
 * press details
 * click on the plus

Observation: event entry detail does not open.
Expectation: should open.

Observations:
 * no entry on browser console
 * after changing the query again, it sometimes works again and may stop next time again

Version: 0.6.7, Test with Chromium

**Comment by wagner-certat** [comment]
We observe that too (sometimes) but I also could find the cause yet

**Comment by bernhardreiter** [comment]
Did another test and could reproduce the problem with
 fody-backend  https://github.com/Intevation/intelmq-fody-backend/releases/tag/v0.6.1 (Feb 2018)
 fody https://github.com/Intevation/intelmq-fody/releases/tag/v0.6.4 (March 2018)

**Comment by bernhardreiter** [comment]
The "plus" icon is within the datatables components, thus events run a little differently compared to other parts of fody.

**Comment by bernhardreiter** [comment]
Starting to work on resolving the issue. 
A user reported that sometimes, even a first search did not open.
